### ISSUE TITLE
Step 5 Assign Networks, network name is not "management"

### ISSUE THREAD

**Issue by scottbri** [pivotal-cf/docs-ops-manager#13] opened 2019-01-18 22:36 UTC
when progressing down the PKS installation path, the Assign Networks Network name is actually, "pks-infrastructure-network"

not "management"

**Comment by mjgutermuth** [comment] 2019-02-14 23:09
Hi @scottbri! Which IaaS docs are you looking at?

**Comment by ograves-pivotal** [comment] 2019-02-22 00:10
Mr. Brightwell ( @scottbri )
I have researched this issue and found we are already correcting network name inconsistencies within the documentation.  I have confirmed your concerns are being handled as part of that process.  For now I am closing this issue as a 'dupe' of our larger task.

Thank you for your observation and filing this issue!

**Closed by ograves-pivotal** 2019-02-22 00:10 UTC
Labels: delivered
